@startuml

title __FDV.AUTHENTICATION.SOAP.MESSAGES's Class Diagram__\n

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ActionType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ActiveParticipantType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AdviceType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AgreementMethodType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AllowPostdatingType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.Anonymous {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AppliesTo {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AssertionType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AttributeStatementType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AttributeType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AttributedAnyType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AttributedDateTime {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AttributedQNameType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AttributedQNameType_1 {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AttributedString {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AttributedURI {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AttributedURIType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AttributedUnsignedLongType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AudienceRestrictionType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AuditMessage {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AuditMessage_ActiveParticipant {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AuditSourceIdentificationType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AuthenticatorType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AuthnContextType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AuthnStatementType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.AuthzDecisionStatementType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.BaseIDAbstractType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.BinaryExchangeType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.BinarySecretType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.BinarySecurityTokenType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.CancelTargetType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.CanonicalizationMethodType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.CipherDataType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.CipherReferenceType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ClaimsType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.CodedValueType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ConditionAbstractType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ConditionsType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.DHKeyValueType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.DSAKeyValueType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.DelegateToType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.DigestMethodType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.EmbeddedType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.EncodedString {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.EncryptedDataType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.EncryptedElementType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.EncryptedKeyType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.EncryptedType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.EncryptionMethodType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.EncryptionPropertiesType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.EncryptionPropertyType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.EncryptionType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.EndpointReferenceType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.EntropyType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.Enums {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.Error {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.Error_Trace {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.Error_Trace_Detail {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.EventIdentificationType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.EvidenceType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ExtendedSoapSerializationEnvelope {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.Functions {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.GetAuditEventsResponse {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.Helper {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    interface de.gematik.ti.epa.fdv.gen.authentication.IServiceEvents {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.I_Authentication_Insurant_Binding_Soap12 {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.KeyExchangeTokenType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.KeyIdentifierType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.KeyInfoConfirmationDataType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.KeyInfoType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.KeyValueType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.LifetimeType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ManifestType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.MarshalGuid {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.MetadataType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.NameIDType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ObjectType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.OnBehalfOfType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.OneTimeUseType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.OperationResult {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.OperatorContentType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.PGPDataType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ParticipantObjectIdentificationType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ParticipantType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ParticipantsType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.PasswordString {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.Policy {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.PolicyAttachment {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.PolicyReference {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ProblemActionType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ProofEncryptionType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ProxyRestrictionType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.RSAKeyValueType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ReferenceList {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ReferenceParametersType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ReferenceType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ReferenceType_1 {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ReferenceType_2 {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.RelatesToType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.RenewTargetType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.RenewingType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.RequestKETType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.RequestSecurityTokenCollectionType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.RequestSecurityTokenResponseCollectionType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.RequestSecurityTokenResponseType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.RequestSecurityTokenType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.RequestedProofTokenType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.RequestedReferenceType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.RequestedSecurityTokenType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.RequestedTokenCancelledType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.RetrievalMethodType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SPKIDataType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SecondaryParameters {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SecurityHeaderType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SecurityTokenReferenceType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ServiceNameType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SignChallengeType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SignatureMethodType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SignaturePropertiesType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SignaturePropertyType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SignatureType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SignatureValueType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SignedInfoType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.StatementAbstractType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.StatusType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SubjectConfirmationDataType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SubjectConfirmationType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SubjectLocalityType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.SubjectType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.TimestampType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.TransformType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.TransformationParametersType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.TransformsType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.TransformsType_1 {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.TypeValuePairType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.UseKeyType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.UsernameTokenType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.UsingAddressing {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.ValidateTargetType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.X509DataType {
    }
  }
  

  namespace de.gematik.ti.epa.fdv.gen.authentication {
    class de.gematik.ti.epa.fdv.gen.authentication.X509IssuerSerialType {
    }
  }
  

  de.gematik.ti.epa.fdv.gen.authentication.ActiveParticipantType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AdviceType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AgreementMethodType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AllowPostdatingType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AppliesTo .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AssertionType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AttributeStatementType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AttributeType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AttributedAnyType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AudienceRestrictionType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AuditMessage .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AuditMessage_ActiveParticipant .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AuditSourceIdentificationType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AuthenticatorType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AuthnContextType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AuthnStatementType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.AuthzDecisionStatementType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.BaseIDAbstractType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.CancelTargetType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.CanonicalizationMethodType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.CipherDataType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.CipherReferenceType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ClaimsType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.CodedValueType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ConditionAbstractType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ConditionsType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.DHKeyValueType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.DSAKeyValueType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.DelegateToType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.DigestMethodType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.EmbeddedType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.EncryptedDataType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.EncryptedElementType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.EncryptedKeyType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.EncryptedType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.EncryptionMethodType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.EncryptionPropertiesType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.EncryptionPropertyType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.EncryptionType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.EndpointReferenceType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.EntropyType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.Error .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.Error_Trace .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.EventIdentificationType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.EvidenceType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.GetAuditEventsResponse .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.KeyExchangeTokenType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.KeyInfoConfirmationDataType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.KeyInfoType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.KeyValueType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.LifetimeType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ManifestType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.MarshalGuid .up.|> Marshal
  de.gematik.ti.epa.fdv.gen.authentication.MetadataType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ObjectType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.OnBehalfOfType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.OneTimeUseType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.OperationResult o-- T : Result
  de.gematik.ti.epa.fdv.gen.authentication.OperatorContentType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.PGPDataType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ParticipantObjectIdentificationType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ParticipantType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ParticipantsType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.Policy .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.PolicyAttachment .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.PolicyReference .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ProblemActionType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ProofEncryptionType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ProxyRestrictionType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.RSAKeyValueType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ReferenceList .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ReferenceParametersType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ReferenceType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ReferenceType_1 .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ReferenceType_2 .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.RenewTargetType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.RenewingType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.RequestKETType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.RequestSecurityTokenCollectionType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.RequestSecurityTokenCollectionType -up-|> java.util.Vector
  de.gematik.ti.epa.fdv.gen.authentication.RequestSecurityTokenResponseCollectionType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.RequestSecurityTokenResponseCollectionType -up-|> java.util.Vector
  de.gematik.ti.epa.fdv.gen.authentication.RequestSecurityTokenResponseType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.RequestSecurityTokenType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.RequestedProofTokenType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.RequestedReferenceType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.RequestedSecurityTokenType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.RequestedTokenCancelledType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.RetrievalMethodType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.SPKIDataType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.SecondaryParameters .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.SecurityHeaderType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.SecurityTokenReferenceType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.SignChallengeType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.SignatureMethodType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.SignaturePropertiesType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.SignaturePropertyType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.SignatureType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.SignedInfoType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.StatementAbstractType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.StatusType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.SubjectConfirmationDataType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.SubjectConfirmationType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.SubjectLocalityType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.SubjectType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.TimestampType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.TransformType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.TransformationParametersType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.TransformsType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.TransformsType -up-|> java.util.Vector
  de.gematik.ti.epa.fdv.gen.authentication.TransformsType_1 .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.TransformsType_1 -up-|> java.util.Vector
  de.gematik.ti.epa.fdv.gen.authentication.TypeValuePairType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.UseKeyType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.UsernameTokenType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.UsingAddressing .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.ValidateTargetType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.X509DataType .up.|> KvmSerializable
  de.gematik.ti.epa.fdv.gen.authentication.X509IssuerSerialType .up.|> KvmSerializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
